# Generated by Django 5.0.8 on 2024-08-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"ordering": ["-timestamp"]},
        ),
    ]
