# Generated by Django 5.0.8 on 2024-08-25 14:31

import exports.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=exports.models.export_file_handler,
                    ),
                ),
                ("timestamps", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
