# Generated by Django 5.0.8 on 2024-08-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating_avg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
