# Generated by Django 5.0.8 on 2024-08-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_rating_avg_movie_rating_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="score",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
